version: '3'
services:
  web:
    image: nginx
    container_name: website_nginx
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.website.service=website"
      - "traefik.http.routers.website.rule=Host(`staf.dev`, `www.staf.dev`)"
      - "traefik.http.routers.website.tls.certresolver=cloudflare"
      - "traefik.http.services.website.loadbalancer.server.port=8888"

networks:
  proxy:
    external: true
